### ISSUE TITLE
Notification Service (send e-mails to users) 

### ISSUE THREAD

**Issue by jadsanders** [sofort-impfen-de/services#15]
User Story
As a user I want to get notified by e-mail automatically if a vaccine appointment for me is available.

Acceptance criteria

- A notification service exists
- This services sends an email to all relevant users once a doctor publishes a slot
- The email includes a link to the users app (available appointments view)
- The service features a throttling mechanism to ensure, that users will not get spammed if several doctors in the same 50km zip area radius publish appointments on short time one after the other (maybe 1 mail per hour per user max., but this is TBD)

**Comment by svettwer** [comment]
Yesterday, we discussed that there should also be an mail-throttling functionality, so that users don't get spammed if multiple doctors push appointments of the same zip code area subsequently.
Should we add this to the acceptance criteria or would you like to separate this functionality to a dedicated issue? Theoretically, we could release the service without the throttling and add it a few days later.

**Comment by jadsanders** [comment]
Good point! I would include it directly in the acceptance criteria if it is not a blocker for a fast roll-out (so if this features would delay the rollout of this service for about a week or so, it would treat it separately). What do you think?

**Comment by svettwer** [comment]
Okay, then let us add it to the acceptance criteria.
If the service is ready to be deployed based on the current AC, the throttling would just add a few hours more of work.

**Comment by jadsanders** [comment]
ok done
